name: 功能建議
description: 為這個範本提出新點子
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Feel free to write in English.

        感謝提出建議！
  - type: textarea
    id: problem
    attributes:
      label: 這個建議想解決什麼問題？
      description: 你想做的事，範本現在還不支援的地方是什麼？
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: 你建議的解法
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 考慮過的替代方案
  - type: checkboxes
    id: would-you-pr
    attributes:
      label: 貢獻意願
      options:
        - label: 我願意為此開一個 PR
